import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { getStaticProps } from "./api/static";
import {
  Key,
  ReactElement,
  JSXElementConstructor,
  ReactNode,
  ReactPortal,
  PromiseLikeOfReactNode,
} from "react";

interface HomeProps {
  pokemons: {
    id: Key | null | undefined;
    name:
      | string
      | number
      | boolean
      | ReactElement<any, string | JSXElementConstructor<any>>
      | Iterable<ReactNode>
      | ReactPortal
      | PromiseLikeOfReactNode
      | null
      | undefined;
  }[];
}

export default function Home({ pokemons }: HomeProps) {
  return (
    <>
      <Head>
        <title>Pokemons</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="mb-8 text-4xl font-bold text-white">Pokemons</h1>
        <div className="grid grid-cols-4 gap-4">
          {pokemons?.map(
            (pokemon: {
              id: Key | null | undefined;
              name:
                | string
                | number
                | boolean
                | ReactElement<any, string | JSXElementConstructor<any>>
                | Iterable<ReactNode>
                | ReactPortal
                | PromiseLikeOfReactNode
                | null
                | undefined;
            }) => (
              <Link href={`/pokemon/${pokemon.id}`} key={pokemon.id}>
                <div className="flex flex-col items-center justify-center rounded-md bg-white p-4">
                  <h2 className="text-2xl font-bold text-gray-800">
                    {pokemon.name}
                  </h2>
                </div>
              </Link>
            ),
          )}
        </div>
      </main>
    </>
  );
}

export { getStaticProps };
